import {
  CANCELED_HOTKEY,
  FIX_PLATE_LEFT_NUMBER_KEY,
  FIX_PLATE_RIGHT_NUMBER_KEY,
  FOCUS_CARD_INPUT_LEFT_KEY,
  FOCUS_CARD_INPUT_RIGHT_KEY,
  HELP_KEY,
  REFRESH_HOTKEY,
  SUBMIT_LEFT_HOTKEY,
  SUBMIT_RIGHT_HOTKEY,
} from "../../../hotkeys/key";

export const HotKeyTableHeaders = ["Phím tắt", "Chức năng"];

export const HotKeyContents = [
  FOCUS_CARD_INPUT_LEFT_KEY,
  FOCUS_CARD_INPUT_RIGHT_KEY,
  FIX_PLATE_LEFT_NUMBER_KEY,
  FIX_PLATE_RIGHT_NUMBER_KEY,
  SUBMIT_LEFT_HOTKEY,
  SUBMIT_RIGHT_HOTKEY,
  CANCELED_HOTKEY,
  REFRESH_HOTKEY,
  HELP_KEY,
];
