import {
  CANCEL_LEFT_HOTKEY,
  CANCEL_RIGHT_HOTKEY,
  FIX_PLATE_LEFT_NUMBER_KEY,
  FIX_PLATE_RIGHT_NUMBER_KEY,
  FOCUS_CARD_INPUT_LEFT_KEY,
  FOCUS_CARD_INPUT_RIGHT_KEY,
  HELP_KEY,
  REFRESH_HOTKEY,
  SUBMIT_LEFT_HOTKEY,
  SUBMIT_RIGHT_HOTKEY,
  SWITCH_LANE_MODE_KEY,
} from "../../../hotkeys/key";

export const HotKeyTableHeaders = ["Phím tắt", "Chức năng"];

export const LeftHotKeys = [
  FOCUS_CARD_INPUT_LEFT_KEY,
  FIX_PLATE_LEFT_NUMBER_KEY,
  SUBMIT_LEFT_HOTKEY,
  CANCEL_LEFT_HOTKEY,
];

export const RightHotKeys = [
  FOCUS_CARD_INPUT_RIGHT_KEY,
  FIX_PLATE_RIGHT_NUMBER_KEY,
  SUBMIT_RIGHT_HOTKEY,
  CANCEL_RIGHT_HOTKEY,
];

export const GeneralHotKeys = [REFRESH_HOTKEY, HELP_KEY, SWITCH_LANE_MODE_KEY];
